# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f0c8cec659362bc0fe330e9317391198978668be95ad4877dfed15da3b7738f0f97f3106edbf1d334283c0df215ec291eef5d12a335b99fe70ec8c673590b5c

test:
  secret_key_base: 36542baf0edd02625877f4076e33d1976a05a8cdf4100d3ccecb78bb6c9d3bbcc8f464a4a12b6397b3939b2e31e47789af774f230b4da1438cfe674d01ad8683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
